Use new iroh blobs methods for file operations
OpenArchive/save-dweb-backend pull request #14
Opened 2024-10-09 20:35 UTC by tripledoublev

Closes hyphacoop/openarchive-dweb-backend#42

2024-10-09 21:27 UTC, RangerMauve requested changes

2024-10-09 21:27 UTC, RangerMauve commented on src/repo.rs
> +            if let Ok(collection_name) = self.iroh_blobs.get_name_from_hash(&collection_hash).await {
We shouldn't need to check the DHT, just check if the name exists in the iroh_blobs store

2024-10-09 21:27 UTC, RangerMauve commented on src/repo.rs
> +        let collection_name = self.iroh_blobs.get_name_from_hash(&collection_hash).await?;
This should not be necessary, the name will always be the repo id

2024-10-09 21:27 UTC, RangerMauve commented on src/repo.rs
> +        let collection_name = self.iroh_blobs.get_name_from_hash(&collection_hash).await?;
Again, we should use the repo name always

2024-10-09 21:50 UTC, tripledoublev commented on src/repo.rs
> +            if let Ok(collection_name) = self.iroh_blobs.get_name_from_hash(&collection_hash).await {
but if im not mistaken, we don't necessarily have the name. for example, if we get an url invitation to join a group.

2024-10-09 22:02 UTC, tripledoublev commented on src/repo.rs
> +            if let Ok(collection_name) = self.iroh_blobs.get_name_from_hash(&collection_hash).await {
ok i get it now :)

2024-10-09 22:11 UTC, tripledoublev commented on src/repo.rs
> +            if let Ok(collection_name) = self.iroh_blobs.get_name_from_hash(&collection_hash).await {
b38d2fde3edde400f42b0b0c7ea5a93fbe83124b

2024-10-09 22:12 UTC, tripledoublev commented on src/repo.rs
> +        let collection_name = self.iroh_blobs.get_name_from_hash(&collection_hash).await?;
bbd6842ca77494ad362d4fd1be9bd03b531126a7

2024-10-09 22:12 UTC, tripledoublev commented on src/repo.rs
> +        let collection_name = self.iroh_blobs.get_name_from_hash(&collection_hash).await?;
c15ec03d89f6ef8c93dad78a8ef64a756106d929

2024-10-10 17:14 UTC, RangerMauve commented
Replaced by #16

2024-10-10 17:14 UTC, closed without merging