Implement iroh blobs
OpenArchive/save-dweb-backend pull request #9
Opened 2024-10-01 15:25 UTC by tripledoublev

Implemented VeilidIrohBlobs
Reworked tests
as part of hyphacoop/openarchive-dweb-backend#20

2024-10-03 17:02 UTC, tripledoublev commented
Great to see that `All checks have passed`

2024-10-03 17:21 UTC, RangerMauve requested changes

2024-10-03 17:21 UTC, RangerMauve commented on src/backend.rs
> +        let node = Node::memory().spawn().await?;
Instead of initializing a node I think we should create a collection from the store in veilid-iroh-blobs. This is okay for now though

2024-10-03 17:21 UTC, RangerMauve commented on src/common.rs
> +    fn get_route_id_blob(&self) -> Vec<u8>;
This only makes sense for Repo and not Group, no? Might be best to move it there instead

2024-10-03 17:21 UTC, RangerMauve commented on src/group.rs
> +    pub async fn upload_blob(&self, file_path: PathBuf, protected_store: &ProtectedStore) -> Result<Hash> {
This should be in the repo

2024-10-03 17:21 UTC, RangerMauve commented on src/group.rs
> +    fn get_route_id_blob(&self) -> Vec<u8> {
This should just be for your repo

2024-10-03 17:21 UTC, RangerMauve commented on src/lib.rs
> +        let mut stream = ReceiverStream::new(receiver);
Should read from the reciever directly without this wrapper

2024-10-03 17:21 UTC, RangerMauve commented on src/repo.rs
> +use crate::constants::{ASK, DATA, DONE, YES, NO, ERR};
These should probably be hidden in the impl details in the veilid-iroh-blobs module.

2024-10-03 17:21 UTC, RangerMauve commented
Looking good so far BTW

2024-10-08 14:43 UTC, RangerMauve approved these changes

2024-10-08 15:51 UTC, merged